# Generated by Django 3.1.6 on 2021-02-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='lineitem_model',
            new_name='lineitem_total',
        ),
    ]
